#!/bin/bash -e

AS_SOURCE="$1"
TARGET_DIR="$2"
PROJECT_BINARY_DIR="`pwd`"
echo "AS_SOURCE=${AS_SOURCE}"
echo "TARGET_DIR=${TARGET_DIR}"
echo "PROJECT_BINARY_DIR=${PROJECT_BINARY_DIR}"

# Function links file, generating subfolder if necessary
makeLink() {
   mkdir -p `dirname "${PROJECT_BINARY_DIR}/autosave/$1"`
   ln -sfn "${AS_SOURCE}/$1" "${PROJECT_BINARY_DIR}/autosave/$1"
}

export -f makeLink
export PROJECT_BINARY_DIR
export AS_SOURCE

# "find" generates a list of paths to any regular file below the source directory
# and calls the makeLink function for every entry.
# NOTE:Semikolon needs to be escaped
if [ ! -f "${PROJECT_BINARY_DIR}/AutosaveSourceLinked" ]; then
  cd "${AS_SOURCE}/"
  echo "Symlinking autosave source..."
  find -type f -exec bash -c "makeLink {}" \;
  touch "${PROJECT_BINARY_DIR}/AutosaveSourceLinked"
fi

# Replacing the Symlink of the top level RELEASE file with a modified copy
rm "${PROJECT_BINARY_DIR}/autosave/configure/RELEASE"
sed -e 's:EPICS_BASE=.\+:EPICS_BASE='${TARGET_DIR}':' "${AS_SOURCE}/configure/RELEASE" > "${PROJECT_BINARY_DIR}/autosave/configure/RELEASE" -e 's/^SUPPORT=/#SUPPORT=/'

# Replacing the Symlink of the top level CONFIG_SITE file with a modified copy
rm "${PROJECT_BINARY_DIR}/autosave/configure/CONFIG_SITE"
sed -e 's:#INSTALL_LOCATION=.\+:INSTALL_LOCATION='${TARGET_DIR}':' "${AS_SOURCE}/configure/CONFIG_SITE" > "${PROJECT_BINARY_DIR}/autosave/configure/CONFIG_SITE"

# Build library
echo "Build autosave library..."
cd "${PROJECT_BINARY_DIR}/autosave"
make -j5 USR_CFLAGS=-w USR_CXXFLAGS=-w
